name: 'CI/CD'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: |
          npm install
        
      - name: Install ESLint
        run: |
          npm install eslint eslint-config-standard eslint-plugin-import eslint-plugin-n eslint-plugin-promise
        
      - name: Run ESLint with Fix
        run: |
          npx eslint --fix ./secondChance-backend/**/*.js ./sentiment/**/*.js
